/* PitchCheck — real league/team/fixture data.
 *
 * Ratings are derived (see app.js: buildLeague) from each club's real
 * 2025-26 final-table goals-for/against per game. Promoted clubs (no
 * top-flight 2025-26 record) use PROMOTED_DEFAULT until they build one.
 *
 * MATCHES holds this season's (2026-27) real August results and real
 * September fixtures for each of the five leagues, as published by
 * footballwebpages.co.uk on 2026-09-03. Update this file with newer
 * results/fixtures as the season goes on — see README.md.
 *
 * Format per match: [date, home, away, homeGoals, awayGoals, kickoff]
 *   - date: "YYYY-MM-DD"
 *   - homeGoals/awayGoals: numbers if played, null if not yet played
 *   - kickoff: "HH:MM" 24h, shown only for unplayed matches (may be omitted)
 *
 * ROSTERS holds each club's real, currently-registered key first-team
 * players by position (GK/DEF/MID/FWD), most-prominent player listed
 * first per position. The 'By Role' market splits a team's modelled
 * goal/card totals across these real names by position share, NOT from
 * per-player statistics — treat individual to-score/booked percentages
 * as estimates, not licensed prop odds. Squads drift as transfers and
 * injuries happen; refresh periodically the same way as MATCHES.
 *
 * REFEREES_BY_LEAGUE holds real, currently-active referees per league
 * with a sourced cards-per-game (cpg) figure and a derived multiplier
 * (mult) relative to that league's own referee-pool average.
 */
(function (global) {
  "use strict";

  var RAW_LEAGUES = {
    epl: {
      name: "Premier League", short: "EPL", country: "England",
      teams: [
        ["Arsenal",56,21,28],["Manchester City",57,25,28],["Manchester United",50,38,28],
        ["Aston Villa",38,30,28],["Liverpool",47,37,28],["Chelsea",48,31,27],
        ["Brentford",44,40,28],["Everton",32,33,28],["Fulham",40,42,28],
        ["Bournemouth",44,46,28],["Brighton",38,35,28],["Sunderland",29,34,28],
        ["Newcastle United",40,42,28],["Crystal Palace",30,34,28],["Leeds United",37,47,28],
        ["Tottenham Hotspur",38,43,28],["Nottingham Forest",26,41,28],
        ["Coventry City",null,null,null],["Ipswich Town",null,null,null],["Hull City",null,null,null]
      ],
      rivalries: [["Arsenal","Tottenham Hotspur"], ["Manchester City","Manchester United"]]
    },
    laliga: {
      name: "La Liga", short: "La Liga", country: "Spain",
      teams: [
        ["Barcelona",95,36,38],["Real Madrid",77,35,38],["Villarreal",72,46,38],
        ["Atlético Madrid",62,44,38],["Real Betis",59,48,38],["Celta Vigo",53,48,38],
        ["Getafe",32,38,38],["Rayo Vallecano",41,44,38],["Valencia",46,55,38],
        ["Real Sociedad",59,61,38],["Espanyol",43,55,38],["Athletic Bilbao",43,58,38],
        ["Sevilla",46,60,38],["Alavés",44,56,38],["Elche",49,57,38],
        ["Levante",47,61,38],["Osasuna",44,50,38],
        ["Racing Santander",null,null,null],["Deportivo La Coruña",null,null,null],["Málaga",null,null,null]
      ],
      rivalries: [["Barcelona","Real Madrid"], ["Sevilla","Real Betis"]]
    },
    seriea: {
      name: "Serie A", short: "Serie A", country: "Italy",
      teams: [
        ["Inter Milan",64,21,27],["AC Milan",43,20,27],["Napoli",41,28,27],
        ["Roma",34,16,26],["Como",44,20,27],["Juventus",43,25,26],
        ["Atalanta",37,24,27],["Sassuolo",34,36,27],["Bologna",35,32,26],
        ["Lazio",26,27,27],["Parma",20,32,27],["Udinese",28,39,26],
        ["Cagliari",29,36,27],["Torino",27,47,27],["Genoa",32,39,27],
        ["Fiorentina",30,39,26],["Lecce",18,36,27],
        ["Venezia",null,null,null],["Frosinone",null,null,null],["Monza",null,null,null]
      ],
      rivalries: [["Inter Milan","AC Milan"], ["Roma","Lazio"]]
    },
    bundesliga: {
      name: "Bundesliga", short: "Bundesliga", country: "Germany",
      teams: [
        ["Bayern Munich",122,36,34],["Borussia Dortmund",70,34,34],["RB Leipzig",66,47,34],
        ["VfB Stuttgart",71,49,34],["TSG Hoffenheim",65,52,34],["Bayer Leverkusen",68,47,34],
        ["SC Freiburg",51,57,34],["Eintracht Frankfurt",61,65,34],["FC Augsburg",45,61,34],
        ["Mainz 05",44,53,34],["Union Berlin",44,58,34],["Borussia Mönchengladbach",42,53,34],
        ["Hamburger SV",40,54,34],["FC Köln",49,63,34],["Werder Bremen",37,60,34],
        ["SV Elversberg",null,null,null],["Schalke 04",null,null,null],["SC Paderborn",null,null,null]
      ],
      rivalries: [["Bayern Munich","Borussia Dortmund"], ["Hamburger SV","Werder Bremen"]]
    },
    ligue1: {
      name: "Ligue 1", short: "Ligue 1", country: "France",
      teams: [
        ["Paris Saint-Germain",74,29,34],["RC Lens",66,35,34],["LOSC Lille",52,37,34],
        ["Olympique Lyonnais",53,40,34],["Olympique de Marseille",63,45,34],["Stade Rennais",59,50,34],
        ["AS Monaco",60,54,34],["RC Strasbourg",58,47,34],["Toulouse FC",47,46,34],
        ["FC Lorient",48,51,34],["Paris FC",47,50,34],["Stade Brestois",43,55,34],
        ["Angers SCO",29,48,34],["Le Havre AC",32,44,34],["AJ Auxerre",34,44,34],
        ["OGC Nice",37,60,34],
        ["Le Mans FC",null,null,null],["ESTAC Troyes",null,null,null]
      ],
      rivalries: [["Paris Saint-Germain","Olympique de Marseille"], ["RC Lens","LOSC Lille"]]
    }
  };

  var EURO_STRENGTH = { epl:1.00, laliga:0.97, bundesliga:0.93, seriea:0.92, ligue1:0.86 };

  var CUPS = [
    { id:"facup", name:"FA Cup", leagueRef:"epl", note:"The First Round Proper draw isn't made until early November — pick any two Premier League sides below for illustrative odds using this season's ratings." },
    { id:"copadelrey", name:"Copa del Rey", leagueRef:"laliga", note:"Top-flight sides enter at the Round of 32, drawn in December. No real pairings exist yet — pick any two La Liga sides below." },
    { id:"coppaitalia", name:"Coppa Italia", leagueRef:"seriea", note:"Serie A sides enter at the Round of 16 in January. No real pairings exist yet — pick any two Serie A sides below." },
    { id:"dfbpokal", name:"DFB-Pokal", leagueRef:"bundesliga", note:"Round 1 was played in August; the Round 2 draw follows in late October. No confirmed pairings yet — pick any two Bundesliga sides below." },
    { id:"coupedefrance", name:"Coupe de France", leagueRef:"ligue1", note:"Ligue 1 sides enter at the Round of 64 in January. No real pairings exist yet — pick any two Ligue 1 sides below." }
  ];

  // Real 2026-27 results (August) and real fixtures (September), source: footballwebpages.co.uk, snapshot 2026-09-03.
  var MATCHES = {
    epl: [
      ["2026-08-21","Arsenal","Coventry City",3,0],
      ["2026-08-22","Brentford","Tottenham Hotspur",3,0],
      ["2026-08-22","Everton","Crystal Palace",2,0],
      ["2026-08-22","Hull City","Manchester United",2,0],
      ["2026-08-22","Ipswich Town","Sunderland",2,1],
      ["2026-08-22","Nottingham Forest","Leeds United",0,1],
      ["2026-08-23","Brighton","Aston Villa",4,0],
      ["2026-08-23","Manchester City","Bournemouth",2,1],
      ["2026-08-23","Newcastle United","Liverpool",2,2],
      ["2026-08-24","Fulham","Chelsea",2,3],
      ["2026-08-28","Crystal Palace","Manchester City",1,4],
      ["2026-08-29","Bournemouth","Everton",1,1],
      ["2026-08-29","Coventry City","Hull City",0,1],
      ["2026-08-29","Liverpool","Nottingham Forest",2,2],
      ["2026-08-29","Tottenham Hotspur","Newcastle United",0,2],
      ["2026-08-30","Chelsea","Brighton",4,3],
      ["2026-08-30","Leeds United","Brentford",1,1],
      ["2026-08-30","Manchester United","Ipswich Town",5,2],
      ["2026-08-30","Sunderland","Fulham",1,0],
      ["2026-08-31","Aston Villa","Arsenal",0,1],
      ["2026-09-04","Ipswich Town","Liverpool",0,2,null],
      ["2026-09-05","Brentford","Sunderland",1,1,null],
      ["2026-09-05","Brighton","Leeds United",1,1,null],
      ["2026-09-05","Fulham","Crystal Palace",2,3,null],
      ["2026-09-05","Hull City","Aston Villa",0,0,null],
      ["2026-09-05","Manchester City","Coventry City",1,0,null],
      ["2026-09-05","Newcastle United","Bournemouth",2,2,null],
      ["2026-09-05","Nottingham Forest","Tottenham Hotspur",0,0,null],
      ["2026-09-06","Arsenal","Chelsea",null,null,"16:30"],
      ["2026-09-06","Everton","Manchester United",null,null,"14:00"],
      ["2026-09-12","Bournemouth","Brentford",null,null,"15:00"],
      ["2026-09-12","Aston Villa","Nottingham Forest",null,null,"15:00"],
      ["2026-09-12","Chelsea","Hull City",null,null,"15:00"],
      ["2026-09-12","Crystal Palace","Ipswich Town",null,null,"15:00"],
      ["2026-09-12","Liverpool","Fulham",null,null,"15:00"],
      ["2026-09-12","Sunderland","Arsenal",null,null,"20:00"],
      ["2026-09-12","Tottenham Hotspur","Everton",null,null,"17:30"],
      ["2026-09-13","Coventry City","Brighton",null,null,"14:00"],
      ["2026-09-13","Manchester United","Manchester City",null,null,"16:30"],
      ["2026-09-14","Leeds United","Newcastle United",null,null,"20:00"],
      ["2026-09-18","Brentford","Chelsea",null,null,"20:00"],
      ["2026-09-19","Brighton","Arsenal",null,null,"15:00"],
      ["2026-09-19","Everton","Ipswich Town",null,null,"15:00"],
      ["2026-09-19","Newcastle United","Hull City",null,null,"15:00"],
      ["2026-09-19","Nottingham Forest","Coventry City",null,null,"17:30"],
      ["2026-09-19","Tottenham Hotspur","Aston Villa",null,null,"12:30"],
      ["2026-09-20","Bournemouth","Liverpool",null,null,"14:00"],
      ["2026-09-20","Fulham","Manchester United",null,null,"16:30"],
      ["2026-09-20","Leeds United","Crystal Palace",null,null,"14:00"],
      ["2026-09-20","Manchester City","Sunderland",null,null,"14:00"]
    ],
    laliga: [
      ["2026-08-15","Alavés","Getafe",3,0],
      ["2026-08-15","Sevilla","Rayo Vallecano",2,1],
      ["2026-08-16","Espanyol","Levante",3,0],
      ["2026-08-16","Racing Santander","Villarreal",2,2],
      ["2026-08-17","Deportivo La Coruña","Elche",1,1],
      ["2026-08-19","Atlético Madrid","Málaga",2,0],
      ["2026-08-20","Rayo Vallecano","Alavés",1,1],
      ["2026-08-21","Real Betis","Real Sociedad",1,0],
      ["2026-08-22","Athletic Bilbao","Sevilla",1,3],
      ["2026-08-22","Espanyol","Real Madrid",1,2],
      ["2026-08-22","Valencia","Celta Vigo",0,0],
      ["2026-08-23","Atlético Madrid","Villarreal",2,2],
      ["2026-08-23","Elche","Barcelona",0,5],
      ["2026-08-23","Getafe","Racing Santander",1,0],
      ["2026-08-24","Málaga","Deportivo La Coruña",1,1],
      ["2026-08-24","Osasuna","Levante",0,0],
      ["2026-08-25","Valencia","Real Betis",0,1],
      ["2026-08-26","Real Madrid","Real Sociedad",4,1],
      ["2026-08-27","Barcelona","Athletic Bilbao",2,0],
      ["2026-08-27","Celta Vigo","Osasuna",1,2],
      ["2026-09-03","Real Sociedad","Celta Vigo",0,0],
      ["2026-09-04","Real Betis","Real Madrid",1,0,null],
      ["2026-09-05","Athletic Bilbao","Atlético Madrid",3,0,null],
      ["2026-09-05","Rayo Vallecano","Racing Santander",null,null,"17:30"],
      ["2026-09-05","Villarreal","Deportivo La Coruña",null,null,"20:00"],
      ["2026-09-06","Alavés","Osasuna",null,null,"17:30"],
      ["2026-09-06","Espanyol","Sevilla",null,null,"20:00"],
      ["2026-09-06","Málaga","Levante",null,null,"17:30"],
      ["2026-09-06","Valencia","Barcelona",null,null,"15:15"],
      ["2026-09-07","Getafe","Celta Vigo",null,null,"18:00"],
      ["2026-09-07","Elche","Real Sociedad",null,null,"20:30"],
      ["2026-09-11","Sevilla","Valencia",null,null,"20:00"],
      ["2026-09-12","Racing Santander","Alavés",null,null,"13:00"],
      ["2026-09-12","Osasuna","Espanyol",null,null,"15:15"],
      ["2026-09-12","Athletic Bilbao","Elche",null,null,"17:30"],
      ["2026-09-12","Real Madrid","Rayo Vallecano",null,null,"20:00"],
      ["2026-09-13","Celta Vigo","Málaga",null,null,"13:00"],
      ["2026-09-13","Levante","Barcelona",null,null,"15:15"],
      ["2026-09-13","Getafe","Deportivo La Coruña",null,null,"17:30"],
      ["2026-09-13","Real Sociedad","Atlético Madrid",null,null,"20:00"],
      ["2026-09-14","Villarreal","Real Betis",null,null,"20:00"],
      ["2026-09-15","Rayo Vallecano","Espanyol",null,null,"18:00"],
      ["2026-09-15","Alavés","Valencia",null,null,"19:00"],
      ["2026-09-15","Elche","Real Madrid",null,null,"20:30"],
      ["2026-09-16","Atlético Madrid","Osasuna",null,null,"18:00"],
      ["2026-09-16","Deportivo La Coruña","Sevilla",null,null,"18:00"],
      ["2026-09-16","Barcelona","Racing Santander",null,null,"20:30"],
      ["2026-09-16","Levante","Athletic Bilbao",null,null,"20:30"],
      ["2026-09-17","Real Betis","Getafe",null,null,"18:00"],
      ["2026-09-17","Málaga","Villarreal",null,null,"20:30"],
      ["2026-09-18","Espanyol","Elche",null,null,"20:00"],
      ["2026-09-19","Osasuna","Rayo Vallecano",null,null,"13:00"],
      ["2026-09-19","Athletic Bilbao","Alavés",null,null,"15:15"],
      ["2026-09-19","Celta Vigo","Racing Santander",null,null,"17:30"],
      ["2026-09-19","Sevilla","Barcelona",null,null,"20:00"],
      ["2026-09-20","Getafe","Málaga",null,null,"13:00"],
      ["2026-09-20","Atlético Madrid","Real Madrid",null,null,"15:15"],
      ["2026-09-20","Deportivo La Coruña","Real Betis",null,null,"17:30"],
      ["2026-09-20","Villarreal","Levante",null,null,"17:30"],
      ["2026-09-20","Valencia","Real Sociedad",null,null,"20:00"]
    ],
    seriea: [
      ["2026-08-22","Genoa","Napoli",0,2],
      ["2026-08-22","Inter Milan","Monza",4,1],
      ["2026-08-22","Parma","Cagliari",0,1],
      ["2026-08-22","Udinese","Como",1,1],
      ["2026-08-23","Atalanta","Sassuolo",2,1],
      ["2026-08-23","Frosinone","Juventus",0,1],
      ["2026-08-23","Torino","AC Milan",1,2],
      ["2026-08-23","Venezia","Lecce",0,2],
      ["2026-08-24","Bologna","Lazio",0,1],
      ["2026-08-24","Roma","Fiorentina",4,0],
      ["2026-08-28","AC Milan","Venezia",2,0],
      ["2026-08-29","Fiorentina","Frosinone",0,3],
      ["2026-08-29","Juventus","Parma",2,0],
      ["2026-08-29","Monza","Udinese",2,3],
      ["2026-08-29","Sassuolo","Torino",2,1],
      ["2026-08-30","Cagliari","Inter Milan",0,1],
      ["2026-08-30","Lazio","Genoa",1,0],
      ["2026-08-30","Napoli","Como",1,2],
      ["2026-08-31","Atalanta","Bologna",1,0],
      ["2026-08-31","Lecce","Roma",0,4],
      ["2026-09-04","Genoa","Como",1,4,null],
      ["2026-09-05","Fiorentina","Torino",null,null,"14:00"],
      ["2026-09-05","Inter Milan","Napoli",3,2,null],
      ["2026-09-05","Roma","Atalanta",null,null,"19:45"],
      ["2026-09-06","Frosinone","Venezia",null,null,"14:00"],
      ["2026-09-06","Bologna","Sassuolo",null,null,"17:00"],
      ["2026-09-06","Parma","Monza",null,null,"14:00"],
      ["2026-09-06","Juventus","AC Milan",null,null,"19:45"],
      ["2026-09-07","Cagliari","Lecce",null,null,"17:30"],
      ["2026-09-07","Udinese","Lazio",null,null,"19:45"],
      ["2026-09-11","Venezia","Fiorentina",null,null,"19:45"],
      ["2026-09-12","Genoa","Frosinone",null,null,"14:00"],
      ["2026-09-12","Lazio","AC Milan",null,null,"17:00"],
      ["2026-09-12","Atalanta","Cagliari",null,null,"19:45"],
      ["2026-09-13","Lecce","Monza",null,null,"14:00"],
      ["2026-09-13","Napoli","Bologna",null,null,"17:00"],
      ["2026-09-13","Sassuolo","Juventus",null,null,"19:45"],
      ["2026-09-14","Como","Parma",null,null,"17:30"],
      ["2026-09-14","Torino","Roma",null,null,"17:30"],
      ["2026-09-14","Inter Milan","Udinese",null,null,"19:45"],
      ["2026-09-18","Monza","Sassuolo",null,null,"19:45"],
      ["2026-09-19","Bologna","Torino",null,null,"14:00"],
      ["2026-09-19","Udinese","Cagliari",null,null,"14:00"],
      ["2026-09-19","Roma","Inter Milan",null,null,"17:00"],
      ["2026-09-19","Venezia","Lazio",null,null,"19:45"],
      ["2026-09-20","Fiorentina","Napoli",null,null,"11:30"],
      ["2026-09-20","Frosinone","Como",null,null,"14:00"],
      ["2026-09-20","Parma","Genoa",null,null,"14:00"],
      ["2026-09-20","Juventus","Atalanta",null,null,"17:00"],
      ["2026-09-20","AC Milan","Lecce",null,null,"19:45"]
    ],
    bundesliga: [
      ["2026-08-28","Bayern Munich","VfB Stuttgart",5,1],
      ["2026-08-29","FC Köln","TSG Hoffenheim",3,2],
      ["2026-08-29","Borussia Dortmund","Hamburger SV",2,0],
      ["2026-08-29","Mainz 05","SC Paderborn",0,0],
      ["2026-08-29","RB Leipzig","Borussia Mönchengladbach",3,0],
      ["2026-08-29","SV Elversberg","Bayer Leverkusen",3,2],
      ["2026-08-29","Union Berlin","Eintracht Frankfurt",3,3],
      ["2026-08-30","FC Augsburg","Schalke 04",3,0],
      ["2026-08-30","SC Freiburg","Werder Bremen",4,1],
      ["2026-09-04","VfB Stuttgart","FC Köln",4,1,null],
      ["2026-09-05","Bayer Leverkusen","Union Berlin",null,null,"14:30"],
      ["2026-09-05","Borussia Mönchengladbach","SV Elversberg",null,null,"14:30"],
      ["2026-09-05","SC Paderborn","SC Freiburg",null,null,"14:30"],
      ["2026-09-05","TSG Hoffenheim","Borussia Dortmund",null,null,"14:30"],
      ["2026-09-05","Werder Bremen","RB Leipzig",3,1,null],
      ["2026-09-05","Schalke 04","Bayern Munich",0,0,null],
      ["2026-09-06","Hamburger SV","Mainz 05",null,null,"14:30"],
      ["2026-09-06","Eintracht Frankfurt","FC Augsburg",null,null,"16:30"],
      ["2026-09-11","Union Berlin","Schalke 04",null,null,"19:30"],
      ["2026-09-12","FC Augsburg","Bayer Leverkusen",null,null,"14:30"],
      ["2026-09-12","Borussia Dortmund","SC Paderborn",null,null,"14:30"],
      ["2026-09-12","SC Freiburg","Borussia Mönchengladbach",null,null,"14:30"],
      ["2026-09-12","TSG Hoffenheim","VfB Stuttgart",null,null,"14:30"],
      ["2026-09-12","Mainz 05","Eintracht Frankfurt",null,null,"14:30"],
      ["2026-09-12","FC Köln","Werder Bremen",null,null,"17:30"],
      ["2026-09-13","RB Leipzig","Hamburger SV",null,null,"14:30"],
      ["2026-09-13","SV Elversberg","Bayern Munich",null,null,"16:30"],
      ["2026-09-18","Bayern Munich","Union Berlin",null,null,"19:30"],
      ["2026-09-19","Borussia Mönchengladbach","Mainz 05",null,null,"14:30"],
      ["2026-09-19","Eintracht Frankfurt","SC Freiburg",null,null,"14:30"],
      ["2026-09-19","Hamburger SV","FC Köln",null,null,"14:30"],
      ["2026-09-19","Werder Bremen","FC Augsburg",null,null,"14:30"],
      ["2026-09-19","VfB Stuttgart","Borussia Dortmund",null,null,"17:30"],
      ["2026-09-20","Bayer Leverkusen","RB Leipzig",null,null,"14:30"],
      ["2026-09-20","Schalke 04","SV Elversberg",null,null,"16:30"],
      ["2026-09-20","SC Paderborn","TSG Hoffenheim",null,null,"18:30"]
    ],
    ligue1: [
      ["2026-08-21","Olympique de Marseille","RC Strasbourg",4,0],
      ["2026-08-22","Le Mans FC","Stade Brestois",2,2],
      ["2026-08-22","RC Lens","AJ Auxerre",5,2],
      ["2026-08-22","OGC Nice","FC Lorient",0,0],
      ["2026-08-22","Toulouse FC","Olympique Lyonnais",0,2],
      ["2026-08-22","ESTAC Troyes","Paris FC",0,0],
      ["2026-08-23","Angers SCO","LOSC Lille",0,2],
      ["2026-08-23","Le Havre AC","AS Monaco",0,1],
      ["2026-08-23","Stade Rennais","Paris Saint-Germain",2,2],
      ["2026-08-28","LOSC Lille","Paris Saint-Germain",2,2],
      ["2026-08-29","AJ Auxerre","Angers SCO",1,3],
      ["2026-08-29","Stade Brestois","Toulouse FC",2,2],
      ["2026-08-29","FC Lorient","ESTAC Troyes",1,2],
      ["2026-08-29","Olympique Lyonnais","Le Havre AC",1,1],
      ["2026-08-29","RC Strasbourg","RC Lens",2,1],
      ["2026-08-30","AS Monaco","Olympique de Marseille",2,0],
      ["2026-08-30","Paris FC","OGC Nice",3,0],
      ["2026-08-30","Stade Rennais","Le Mans FC",3,2],
      ["2026-09-03","Toulouse FC","LOSC Lille",0,1],
      ["2026-09-04","Olympique Lyonnais","AJ Auxerre",3,1,null],
      ["2026-09-04","Paris Saint-Germain","AS Monaco",1,2,null],
      ["2026-09-05","RC Lens","FC Lorient",0,1,null],
      ["2026-09-05","Le Havre AC","Stade Brestois",null,null,"19:45"],
      ["2026-09-05","OGC Nice","Le Mans FC",null,null,"19:45"],
      ["2026-09-06","ESTAC Troyes","RC Strasbourg",null,null,"14:00"],
      ["2026-09-06","Angers SCO","Stade Rennais",null,null,"16:15"],
      ["2026-09-06","Olympique de Marseille","Paris FC",null,null,"19:45"],
      ["2026-09-11","Stade Rennais","Olympique de Marseille",null,null,"19:45"],
      ["2026-09-12","AJ Auxerre","OGC Nice",null,null,"19:45"],
      ["2026-09-12","Le Havre AC","Angers SCO",null,null,"19:45"],
      ["2026-09-12","FC Lorient","Toulouse FC",null,null,"19:45"],
      ["2026-09-12","Paris FC","Olympique Lyonnais",null,null,"19:45"],
      ["2026-09-12","RC Strasbourg","AS Monaco",null,null,"16:15"],
      ["2026-09-13","LOSC Lille","ESTAC Troyes",null,null,"14:00"],
      ["2026-09-13","Le Mans FC","RC Lens",null,null,"16:15"],
      ["2026-09-13","Stade Brestois","Paris Saint-Germain",null,null,"19:45"],
      ["2026-09-18","AS Monaco","RC Lens",null,null,"19:45"],
      ["2026-09-19","Angers SCO","ESTAC Troyes",null,null,"19:45"],
      ["2026-09-19","Le Mans FC","FC Lorient",null,null,"19:45"],
      ["2026-09-19","Olympique Lyonnais","Stade Rennais",null,null,"19:45"],
      ["2026-09-19","Paris FC","RC Strasbourg",null,null,"16:15"],
      ["2026-09-19","Toulouse FC","Le Havre AC",null,null,"19:45"],
      ["2026-09-20","AJ Auxerre","Stade Brestois",null,null,"14:00"],
      ["2026-09-20","OGC Nice","LOSC Lille",null,null,"16:15"],
      ["2026-09-20","Olympique de Marseille","Paris Saint-Germain",null,null,"19:45"]
    ]
  };


var ROSTERS = {
"Arsenal": [["David Raya","GK"],["William Saliba","DEF"],["Gabriel Magalhães","DEF"],["Jurriën Timber","DEF"],["Riccardo Calafiori","DEF"],["Declan Rice","MID"],["Martín Zubimendi","MID"],["Bruno Guimarães","MID"],["Bukayo Saka","FWD"],["Viktor Gyökeres","FWD"],["Kai Havertz","FWD"]],
"Manchester City": [["Gianluigi Donnarumma","GK"],["Rúben Dias","DEF"],["Joško Gvardiol","DEF"],["Abdukodir Khusanov","DEF"],["Nico O'Reilly","DEF"],["Phil Foden","MID"],["Enzo Fernández","MID"],["Mateo Kovačić","MID"],["Erling Haaland","FWD"],["Jeremy Doku","FWD"],["Rayan Cherki","FWD"]],
"Manchester United": [["Senne Lammens","GK"],["Lisandro Martínez","DEF"],["Diogo Dalot","DEF"],["Noussair Mazraoui","DEF"],["Leny Yoro","DEF"],["Bruno Fernandes","MID"],["Kobbie Mainoo","MID"],["Amad Diallo","MID"],["Bryan Mbeumo","FWD"],["Matheus Cunha","FWD"],["Benjamin Šeško","FWD"]],
"Aston Villa": [["Zion Suzuki","GK"],["Matty Cash","DEF"],["Pau Torres","DEF"],["Ian Maatsen","DEF"],["Tyrone Mings","DEF"],["John McGinn","MID"],["Boubacar Kamara","MID"],["Leon Goretzka","MID"],["Nicolas Jackson","FWD"],["Emiliano Buendía","FWD"],["Alejandro Garnacho","FWD"]],
"Liverpool": [["Alisson Becker","GK"],["Virgil van Dijk","DEF"],["Milos Kerkez","DEF"],["Jeremie Frimpong","DEF"],["Joe Gomez","DEF"],["Florian Wirtz","MID"],["Dominik Szoboszlai","MID"],["Alexis Mac Allister","MID"],["Alexander Isak","FWD"],["Hugo Ekitike","FWD"],["Cody Gakpo","FWD"]],
"Chelsea": [["Robert Sánchez","GK"],["Reece James","DEF"],["Levi Colwill","DEF"],["Jorrel Hato","DEF"],["Malo Gusto","DEF"],["Cole Palmer","MID"],["Enzo Fernández","MID"],["Moisés Caicedo","MID"],["João Pedro","FWD"],["Pedro Neto","FWD"],["Liam Delap","FWD"]],
"Brentford": [["Caoimhín Kelleher","GK"],["Nathan Collins","DEF"],["Keane Lewis-Potter","DEF"],["Kristoffer Ajer","DEF"],["Rico Henry","DEF"],["Mathias Jensen","MID"],["Mikkel Damsgaard","MID"],["Yehor Yarmoliuk","MID"],["Igor Thiago","FWD"],["Kevin Schade","FWD"],["Dango Ouattara","FWD"]],
"Everton": [["Jordan Pickford","GK"],["James Tarkowski","DEF"],["Jarrad Branthwaite","DEF"],["Vitaliy Mykolenko","DEF"],["Michael Keane","DEF"],["James Garner","MID"],["Kiernan Dewsbury-Hall","MID"],["Carlos Alcaraz","MID"],["Iliman Ndiaye","FWD"],["Thierno Barry","FWD"],["Beto","FWD"]],
"Fulham": [["Bernd Leno","GK"],["Joachim Andersen","DEF"],["Calvin Bassey","DEF"],["Antonee Robinson","DEF"],["Timothy Castagne","DEF"],["Sander Berge","MID"],["Alex Iwobi","MID"],["Harrison Reed","MID"],["Rodrigo Muniz","FWD"],["Emile Smith Rowe","FWD"],["Oscar Bobb","FWD"]],
"Bournemouth": [["Djordje Petrović","GK"],["Adrien Truffert","DEF"],["Bafodé Diakité","DEF"],["Antonio Silva","DEF"],["James Hill","DEF"],["Alex Scott","MID"],["Marcus Tavernier","MID"],["Lewis Cook","MID"],["Evanilson","FWD"],["Justin Kluivert","FWD"],["David Brooks","FWD"]],
"Brighton": [["Bart Verbruggen","GK"],["Lewis Dunk","DEF"],["Mats Wieffer","DEF"],["Pascal Struijk","DEF"],["Ferdi Kadıoğlu","DEF"],["Pascal Groß","MID"],["Jack Hinshelwood","MID"],["Yasin Ayari","MID"],["Kaoru Mitoma","FWD"],["Georginio Rutter","FWD"],["Yankuba Minteh","FWD"]],
"Sunderland": [["Anthony Patterson","GK"],["Dennis Cirkin","DEF"],["Daniel Ballard","DEF"],["Luke O'Nien","DEF"],["Trai Hume","DEF"],["Dan Neil","MID"],["Chris Rigg","MID"],["Patrick Roberts","MID"],["Wilson Isidor","FWD"],["Eliezer Mayenda","FWD"],["Romaine Mundle","FWD"]],
"Newcastle United": [["Nick Pope","GK"],["Kieran Trippier","DEF"],["Fabian Schär","DEF"],["Sven Botman","DEF"],["Tino Livramento","DEF"],["Joelinton","MID"],["Anthony Gordon","MID"],["Sean Longstaff","MID"],["Yoane Wissa","FWD"],["Anthony Elanga","FWD"],["William Osula","FWD"]],
"Crystal Palace": [["Dean Henderson","GK"],["Daniel Muñoz","DEF"],["Tyrick Mitchell","DEF"],["Chris Richards","DEF"],["Chadi Riad","DEF"],["Adam Wharton","MID"],["Cheick Doucouré","MID"],["Daichi Kamada","MID"],["Jean-Philippe Mateta","FWD"],["Ismaïla Sarr","FWD"],["Eddie Nketiah","FWD"]],
"Leeds United": [["Lucas Perri","GK"],["Ethan Ampadu","DEF"],["Joe Rodon","DEF"],["Jayden Bogle","DEF"],["Sebastiaan Bornauw","DEF"],["Ilia Gruev","MID"],["Ao Tanaka","MID"],["Brenden Aaronson","MID"],["Joel Piroe","FWD"],["Largie Ramazani","FWD"],["Daniel James","FWD"]],
"Tottenham Hotspur": [["Antonín Kinský","GK"],["Pedro Porro","DEF"],["Micky van de Ven","DEF"],["Destiny Udogie","DEF"],["Marcos Senesi","DEF"],["Sandro Tonali","MID"],["James Maddison","MID"],["Rodrigo Bentancur","MID"],["Dominic Solanke","FWD"],["Mohammed Kudus","FWD"],["Richarlison","FWD"]],
"Nottingham Forest": [["Matz Sels","GK"],["Murillo","DEF"],["Ola Aina","DEF"],["Neco Williams","DEF"],["Nikola Milenković","DEF"],["Morgan Gibbs-White","MID"],["Oleksandr Zinchenko","MID"],["Ibrahim Sangaré","MID"],["Chris Wood","FWD"],["Callum Hudson-Odoi","FWD"],["Taiwo Awoniyi","FWD"]],
"Coventry City": [["Ben Wilson","GK"],["Liam Kitching","DEF"],["Luis Binks","DEF"],["Milan van Ewijk","DEF"],["Jake Bidwell","DEF"],["Ben Sheaf","MID"],["Josh Eccles","MID"],["Tatsuhiro Sakamoto","MID"],["Haji Wright","FWD"],["Ellis Simms","FWD"],["Ephron Mason-Clark","FWD"]],
"Ipswich Town": [["Aro Muric","GK"],["Leif Davis","DEF"],["Jacob Greaves","DEF"],["Cameron Burgess","DEF"],["Axel Tuanzebe","DEF"],["Sam Morsy","MID"],["Jens Cajuste","MID"],["Massimo Luongo","MID"],["Omari Hutchinson","FWD"],["George Hirst","FWD"],["Nathan Broadhead","FWD"]],
"Hull City": [["Ivor Pandur","GK"],["Sean McLoughlin","DEF"],["Alfie Jones","DEF"],["Charlie Hughes","DEF"],["Ryan Giles","DEF"],["Jean Michaël Seri","MID"],["Regan Slater","MID"],["Xavier Simons","MID"],["Liam Millar","FWD"],["Noah Ohio","FWD"],["Ben Jackson","FWD"]],

"Barcelona": [["Joan García","GK"],["Jules Koundé","DEF"],["Pau Cubarsí","DEF"],["Alejandro Balde","DEF"],["Andreas Christensen","DEF"],["Pedri","MID"],["Rodri","MID"],["Frenkie de Jong","MID"],["Lamine Yamal","FWD"],["Raphinha","FWD"],["Gabriel Jesus","FWD"]],
"Real Madrid": [["Thibaut Courtois","GK"],["Éder Militão","DEF"],["Antonio Rüdiger","DEF"],["Ibrahima Konaté","DEF"],["Marc Cucurella","DEF"],["Jude Bellingham","MID"],["Federico Valverde","MID"],["Aurélien Tchouaméni","MID"],["Bernardo Silva","MID"],["Kylian Mbappé","FWD"],["Vinícius Júnior","FWD"]],
"Villarreal": [["Péter Gulácsi","GK"],["Juan Foyth","DEF"],["Logan Costa","DEF"],["Renato Veiga","DEF"],["Sergi Cardona","DEF"],["Pape Gueye","MID"],["Santi Comesaña","MID"],["Alberto Moleiro","MID"],["Georges Mikautadze","FWD"],["Gerard Moreno","FWD"],["Ayoze Pérez","FWD"]],
"Atlético Madrid": [["Jan Oblak","GK"],["José María Giménez","DEF"],["Robin Le Normand","DEF"],["Nahuel Molina","DEF"],["Javi Galán","DEF"],["Rodrigo De Paul","MID"],["Koke","MID"],["Pablo Barrios","MID"],["Julián Álvarez","FWD"],["Antoine Griezmann","FWD"],["Alexander Sørloth","FWD"]],
"Real Betis": [["Álvaro Valles","GK"],["Héctor Bellerín","DEF"],["Marc Bartra","DEF"],["Diego Llorente","DEF"],["Chadi Riad","DEF"],["Johnny Cardoso","MID"],["Isco","MID"],["Marc Roca","MID"],["Cucho Hernández","FWD"],["Antony","FWD"],["Ez Abde","FWD"]],
"Celta Vigo": [["Vicente Guaita","GK"],["Óscar Mingueza","DEF"],["Carl Starfelt","DEF"],["Javi Rodríguez","DEF"],["Yoel Lago","DEF"],["Fer López","MID"],["Damián Rodríguez","MID"],["Hugo Sotelo","MID"],["Iago Aspas","FWD"],["Borja Iglesias","FWD"],["Williot Swedberg","FWD"]],
"Getafe": [["David Soria","GK"],["Domingos Duarte","DEF"],["Djené Dakonam","DEF"],["Juan Iglesias","DEF"],["Diego Rico","DEF"],["Mauro Arambarri","MID"],["Luis Milla","MID"],["Nemanja Maksimović","MID"],["Borja Mayoral","FWD"],["Álvaro Rodríguez","FWD"],["Yellu Santiago","FWD"]],
"Rayo Vallecano": [["Stole Dimitrievski","GK"],["Abdul Mumin","DEF"],["Florian Lejeune","DEF"],["Iván Balliu","DEF"],["Alfonso Espino","DEF"],["Óscar Trejo","MID"],["Pathé Ciss","MID"],["Isi Palazón","MID"],["Randy Nteka","FWD"],["Álvaro García","FWD"],["Jorge de Frutos","FWD"]],
"Valencia": [["Julen Agirrezabala","GK"],["José Gayà","DEF"],["Mouctar Diakhaby","DEF"],["César Tárrega","DEF"],["Thierry Correia","DEF"],["Javi Guerra","MID"],["Pepelu","MID"],["Fran Pérez","MID"],["Hugo Duro","FWD"],["Diego López","FWD"],["Rafa Mir","FWD"]],
"Real Sociedad": [["Álex Remiro","GK"],["Aritz Elustondo","DEF"],["Igor Zubeldia","DEF"],["Jon Aramburu","DEF"],["Aihen Muñoz","DEF"],["Beñat Turrientes","MID"],["Sergio Gómez","MID"],["Arsen Zakharyan","MID"],["Mikel Oyarzabal","FWD"],["Take Kubo","FWD"],["Orri Óskarsson","FWD"]],
"Espanyol": [["Marko Dmitrović","GK"],["Omar El Hilali","DEF"],["Leandro Cabrera","DEF"],["Loïc Williams","DEF"],["Brian Oliván","DEF"],["Pol Lozano","MID"],["Edu Expósito","MID"],["Álex Kral","MID"],["Javi Puado","FWD"],["Kike García","FWD"],["Roberto Fernández","FWD"]],
"Athletic Bilbao": [["Unai Simón","GK"],["Dani Vivian","DEF"],["Yeray Álvarez","DEF"],["Óscar de Marcos","DEF"],["Aitor Paredes","DEF"],["Mikel Jauregizar","MID"],["Oihan Sancet","MID"],["Beñat Prados","MID"],["Nico Williams","FWD"],["Iñaki Williams","FWD"],["Gorka Guruzeta","FWD"]],
"Sevilla": [["Álvaro Fernández","GK"],["Kike Salas","DEF"],["Nemanja Gudelj","DEF"],["José Ángel Carmona","DEF"],["Marcão","DEF"],["Saúl Ñíguez","MID"],["Djibril Sow","MID"],["Lucien Agoumé","MID"],["Isaac Romero","FWD"],["Akor Adams","FWD"],["Dodi Lukébakio","FWD"]],
"Alavés": [["Antonio Sivera","GK"],["Abdel Abqar","DEF"],["Nahuel Tenaglia","DEF"],["Manu Sánchez","DEF"],["Diego García","DEF"],["Ander Guevara","MID"],["Antonio Blanco","MID"],["Jon Guridi","MID"],["Samu Omorodion","FWD"],["Toni Martínez","FWD"],["Carlos Vicente","FWD"]],
"Elche": [["Matías Dituro","GK"],["Adrián Butzke","DEF"],["Diego González","DEF"],["Óscar Chust","DEF"],["Álex Sola","DEF"],["Fede Redondo","MID"],["Josan","MID"],["Álvaro Núñez","MID"],["André Silva","FWD"],["Pere Milla","FWD"]],
"Levante": [["Cárdenas","GK"],["Isaac Carcelén","DEF"],["Iván López","DEF"],["Dani Cárdenas","DEF"],["Vencedor","MID"],["Roberto López","MID"],["Carlos Álvarez","MID"],["Karl Etta Eyong","FWD"],["Iván Romero","FWD"]],
"Osasuna": [["Sergio Herrera","GK"],["David García","DEF"],["Alejandro Catena","DEF"],["Jesús Areso","DEF"],["Rubén Peña","DEF"],["Moi Gómez","MID"],["Jon Moncayola","MID"],["Rubén García","MID"],["Ante Budimir","FWD"],["Bryan Zaragoza","FWD"],["Jon Karrikaburu","FWD"]],
"Racing Santander": [["Jokin Ezkieta","GK"],["Manex Lozano","DEF"],["Santi Franco","DEF"],["Kike Márquez","DEF"],["Íñigo Vicente","MID"],["Andrés Martín","MID"],["Javi Castro","MID"],["Jeremy Arévalo","FWD"]],
"Deportivo La Coruña": [["Aarón Escandell","GK"],["Álex Martínez","DEF"],["Ximo Navarro","DEF"],["Loureiro","DEF"],["Yeremay Hermosa","MID"],["David Mella","MID"],["Mario Soriano","MID"],["Lucas Pérez","FWD"],["Riki Villar","FWD"]],
"Málaga": [["Rubén Yáñez","GK"],["Einar Galilea","DEF"],["Haitam Aatit","DEF"],["Manu González","DEF"],["Kevin Medina","DEF"],["Roberto López","MID"],["Antonio Sánchez","MID"],["Antonio Puertas","FWD"],["Dioni Villalba","FWD"]],

"Inter Milan": [["Josep Martínez","GK"],["Alessandro Bastoni","DEF"],["Federico Dimarco","DEF"],["Benjamin Pavard","DEF"],["Manuel Akanji","DEF"],["Nicolò Barella","MID"],["Hakan Çalhanoğlu","MID"],["Henrikh Mkhitaryan","MID"],["Lautaro Martínez","FWD"],["Marcus Thuram","FWD"]],
"AC Milan": [["Mike Maignan","GK"],["Fikayo Tomori","DEF"],["Pervis Estupiñán","DEF"],["Koni De Winter","DEF"],["Strahinja Pavlović","DEF"],["Luka Modrić","MID"],["Adrien Rabiot","MID"],["Ruben Loftus-Cheek","MID"],["Christian Pulišić","FWD"],["Gonçalo Ramos","FWD"],["Samuel Chukwueze","FWD"]],
"Napoli": [["Alex Meret","GK"],["Giovanni Di Lorenzo","DEF"],["Alessandro Buongiorno","DEF"],["Sam Beukema","DEF"],["Mathías Olivera","DEF"],["Kevin De Bruyne","MID"],["Scott McTominay","MID"],["Frank Anguissa","MID"],["Rasmus Højlund","FWD"],["David Neres","FWD"],["Matteo Politano","FWD"]],
"Roma": [["Mile Svilar","GK"],["Gianluca Mancini","DEF"],["Evan Ndicka","DEF"],["Nahuel Molina","DEF"],["Wesley","DEF"],["Lorenzo Pellegrini","MID"],["Manu Koné","MID"],["Bryan Cristante","MID"],["Paulo Dybala","FWD"],["Santiago Castro","FWD"],["Matías Soulé","FWD"]],
"Como": [["Robert Sánchez","GK"],["Trevoh Chalobah","DEF"],["Yan Couto","DEF"],["Willy Kambwala","DEF"],["Álex Valle","DEF"],["Nico Paz","MID"],["Martin Baturina","MID"],["Samuele Ricci","MID"],["Moise Kean","FWD"],["Assane Diao","FWD"],["Jesús Rodríguez","FWD"]],
"Juventus": [["Guglielmo Vicario","GK"],["Bremer","DEF"],["Pierre Kalulu","DEF"],["Andrea Cambiaso","DEF"],["Juan Cabal","DEF"],["Teun Koopmeiners","MID"],["Khéphren Thuram","MID"],["Weston McKennie","MID"],["Kenan Yıldız","FWD"],["Nick Woltemade","FWD"],["Francisco Conceição","FWD"]],
"Atalanta": [["Marco Carnesecchi","GK"],["Giorgio Scalvini","DEF"],["Isak Hien","DEF"],["Odilon Kossounou","DEF"],["Davide Zappacosta","DEF"],["Charles De Ketelaere","MID"],["Éderson","MID"],["Raoul Bellanova","MID"],["Gianluca Scamacca","FWD"],["Giacomo Raspadori","FWD"],["Nikola Krstović","FWD"]],
"Sassuolo": [["Aro Murić","GK"],["Sebastian Walukiewicz","DEF"],["Jay Idzes","DEF"],["Josh Doig","DEF"],["Cas Odenthal","DEF"],["Kristian Thorstvedt","MID"],["Nemanja Matić","MID"],["Daniel Boloca","MID"],["Domenico Berardi","FWD"],["Armand Laurienté","FWD"],["Benjamín Domínguez","FWD"]],
"Bologna": [["Łukasz Skorupski","GK"],["Nadir Zortea","DEF"],["Juan Miranda","DEF"],["Martin Vitík","DEF"],["Emil Holm","DEF"],["Lewis Ferguson","MID"],["Tommaso Pobega","MID"],["Nikola Moro","MID"],["Riccardo Orsolini","FWD"],["Artem Dovbyk","FWD"],["Jesper Karlsson","FWD"]],
"Lazio": [["Christos Mandas","GK"],["Alessio Romagnoli","DEF"],["Adam Marušić","DEF"],["Nuno Tavares","DEF"],["Samuel Gigot","DEF"],["Nicolò Rovella","MID"],["Davide Frattesi","MID"],["Danilo Cataldi","MID"],["Mattia Zaccagni","FWD"],["Boulaye Dia","FWD"],["Gustav Isaksen","FWD"]],
"Parma": [["Giovanni Daffara","GK"],["Enrico Del Prato","DEF"],["Lautaro Valenti","DEF"],["Emanuele Valeri","DEF"],["Diego Carlos","DEF"],["Adrián Bernabé","MID"],["Giovanni Fabbian","MID"],["Hans Nicolussi Caviglia","MID"],["El Bilal Touré","FWD"],["Pontus Almqvist","FWD"],["Matija Frigan","FWD"]],
"Udinese": [["Maduka Okoye","GK"],["Oumar Solet","DEF"],["Christian Kabasele","DEF"],["Enzo Ebosse","DEF"],["Alessandro Zanoli","DEF"],["Nicolò Zaniolo","MID"],["Sandi Lovrić","MID"],["Lennon Miller","MID"],["Keinan Davis","FWD"],["Vakoun Bayo","FWD"]],
"Cagliari": [["Elia Caprile","GK"],["Yerry Mina","DEF"],["Yukinari Sugawara","DEF"],["Adam Obert","DEF"],["Juan Rodriguez","DEF"],["Roberto Gagliardini","MID"],["Daniel Maldini","MID"],["Jacopo Fazzini","MID"],["Kevin Carlos","FWD"],["M'Bala Nzola","FWD"],["Gennaro Borrelli","FWD"]],
"Torino": [["Franco Israel","GK"],["Saúl Coco","DEF"],["Ardian Ismajli","DEF"],["Cristiano Biraghi","DEF"],["Pietro Comuzzo","DEF"],["Nikola Vlašić","MID"],["Rolando Mandragora","MID"],["Cesare Casadei","MID"],["Duván Zapata","FWD"],["Giovanni Simeone","FWD"],["Zakaria Aboukhlal","FWD"]],
"Genoa": [["Justin Bijlow","GK"],["Johan Vásquez","DEF"],["Aarón Martín","DEF"],["Leo Østigård","DEF"],["Stefano Sabelli","DEF"],["Morten Frendrup","MID"],["Djibril Sow","MID"],["Tommaso Baldanzi","MID"],["Vitinha","FWD"],["Lorenzo Colombo","FWD"],["Junior Messias","FWD"]],
"Fiorentina": [["David de Gea","GK"],["Dodô","DEF"],["Luca Ranieri","DEF"],["Marin Pongračić","DEF"],["Fabiano Parisi","DEF"],["Franco Mastantuono","MID"],["Nicolò Fagioli","MID"],["Marco Brescianini","MID"],["Beto","FWD"],["Riccardo Sottil","FWD"],["Pedro Gonçalves","FWD"]],
"Lecce": [["Wladimiro Falcone","GK"],["Antonino Gallo","DEF"],["Kialonda Gaspar","DEF"],["Tiago Gabriel","DEF"],["Danilo Veiga","DEF"],["Ivan Ilić","MID"],["Lassana Coulibaly","MID"],["Medon Berisha","MID"],["Nikola Štulić","FWD"],["Lameck Banda","FWD"],["Santiago Pierotti","FWD"]],
"Venezia": [["Filip Stanković","GK"],["Juan Jesus","DEF"],["Pasquale Mazzocchi","DEF"],["Joël Schingtienne","DEF"],["Ridgeciano Haps","DEF"],["Gianluca Busio","MID"],["Simon Sohm","MID"],["Toma Bašić","MID"],["John Yeboah","FWD"],["Akor Adams","FWD"],["Andrea Adorante","FWD"]],
"Frosinone": [["Matteo Pisseri","GK"],["Kevin Akpoguma","DEF"],["Aleksa Terzić","DEF"],["Ilario Monterisi","DEF"],["Giorgio Cittadini","DEF"],["Romano Schmid","MID"],["Florian Grillitsch","MID"],["Patrizio Masini","MID"],["Daniel Bîrligea","FWD"],["Giorgi Kvernadze","FWD"],["Antonio Raimondo","FWD"]],
"Monza": [["Aljaž Strajnar","GK"],["Andrea Carboni","DEF"],["Jan Ziółkowski","DEF"],["Saba Goglichidze","DEF"],["Samuele Birindelli","DEF"],["Matteo Pessina","MID"],["Andrea Colpani","MID"],["Michael Folorunsho","MID"],["Keita Baldé","FWD"],["Patrick Cutrone","FWD"],["Dany Mota","FWD"]],

"Bayern Munich": [["Manuel Neuer","GK"],["Dayot Upamecano","DEF"],["Jonathan Tah","DEF"],["Alphonso Davies","DEF"],["Kim Min-Jae","DEF"],["Joshua Kimmich","MID"],["Jamal Musiala","MID"],["Konrad Laimer","MID"],["Harry Kane","FWD"],["Michael Olise","FWD"],["Luis Díaz","FWD"]],
"Borussia Dortmund": [["Gregor Kobel","GK"],["Nico Schlotterbeck","DEF"],["Waldemar Anton","DEF"],["Julian Ryerson","DEF"],["Ramy Bensebaïni","DEF"],["Jobe Bellingham","MID"],["Felix Nmecha","MID"],["Emre Can","MID"],["Serhou Guirassy","FWD"],["Maximilian Beier","FWD"],["Fábio Silva","FWD"]],
"RB Leipzig": [["Maarten Vandevoordt","GK"],["Castello Lukeba","DEF"],["Willi Orbán","DEF"],["David Raum","DEF"],["Benjamin Henrichs","DEF"],["Christoph Baumgartner","MID"],["Assan Ouédraogo","MID"],["Rocco Reitz","MID"],["Antonio Nusa","FWD"],["Christopher Nkunku","FWD"],["Johan Bakayoko","FWD"]],
"VfB Stuttgart": [["Fabian Bredlow","GK"],["Jeff Chabot","DEF"],["Ramon Hendriks","DEF"],["Josha Vagnoman","DEF"],["Maximilian Mittelstädt","DEF"],["Angelo Stiller","MID"],["Atakan Karazor","MID"],["Bilal El Khannouss","MID"],["Deniz Undav","FWD"],["Ermedin Demirović","FWD"],["Jamie Leweling","FWD"]],
"TSG Hoffenheim": [["Oliver Baumann","GK"],["Albian Hajdari","DEF"],["Ozan Kabak","DEF"],["Kōki Machida","DEF"],["Valentin Gendrey","DEF"],["Andrej Kramarić","MID"],["Dennis Geiger","MID"],["Wouter Burger","MID"],["Adam Hložek","FWD"],["Fisnik Asllani","FWD"],["Tim Lemperle","FWD"]],
"Bayer Leverkusen": [["Mark Flekken","GK"],["Edmond Tapsoba","DEF"],["Miguel Gutiérrez","DEF"],["Jarell Quansah","DEF"],["Loïc Badé","DEF"],["Aleix García","MID"],["Exequiel Palacios","MID"],["Robert Andrich","MID"],["Patrik Schick","FWD"],["Victor Boniface","FWD"],["Martin Terrier","FWD"]],
"SC Freiburg": [["Florian Müller","GK"],["Matthias Ginter","DEF"],["Christian Günter","DEF"],["Philipp Lienhart","DEF"],["Lukas Kübler","DEF"],["Vincenzo Grifo","MID"],["Maximilian Eggestein","MID"],["Patrick Osterhage","MID"],["Lucas Höler","FWD"],["Igor Matanović","FWD"],["Jan-Niklas Beste","FWD"]],
"Eintracht Frankfurt": [["Noah Atubolu","GK"],["Robin Koch","DEF"],["Arthur Theate","DEF"],["Nnamdi Collins","DEF"],["Lilian Brassier","DEF"],["Mario Götze","MID"],["Can Uzun","MID"],["Farès Chaïbi","MID"],["Jonathan Burkardt","FWD"],["Ritsu Dōan","FWD"],["Ansgar Knauff","FWD"]],
"FC Augsburg": [["Finn Dahmen","GK"],["Jeffrey Gouweleeuw","DEF"],["Keven Schlotterbeck","DEF"],["Mads Pedersen","DEF"],["Chrislain Matsima","DEF"],["Fabian Rieder","MID"],["Alexis Claude-Maurice","MID"],["Kristijan Jakić","MID"],["Michael Gregoritsch","FWD"],["Rodrigo Ribeiro","FWD"],["Nathanaël Mbuku","FWD"]],
"Mainz 05": [["Robin Zentner","GK"],["Andreas Hanche-Olsen","DEF"],["Silvan Widmer","DEF"],["Stefan Posch","DEF"],["Anthony Caci","DEF"],["Nadiem Amiri","MID"],["Jae-sung Lee","MID"],["Dominik Kohr","MID"],["Sheraldo Becker","FWD"],["Ransford Königsdörffer","FWD"],["Benedict Hollerbach","FWD"]],
"Union Berlin": [["Frederik Rønnow","GK"],["Josip Juranović","DEF"],["Leopold Querfeld","DEF"],["Christopher Trimmel","DEF"],["Felix Uduokhai","DEF"],["Rani Khedira","MID"],["András Schäfer","MID"],["Janik Haberer","MID"],["Andrej Ilić","FWD"],["Tim Skarke","FWD"],["Oliver Burke","FWD"]],
"Borussia Mönchengladbach": [["Moritz Nicolas","GK"],["Kō Itakura","DEF"],["Joe Scally","DEF"],["Kevin Diks","DEF"],["Fabio Chiarodia","DEF"],["Kevin Stöger","MID"],["Florian Neuhaus","MID"],["Jens Castrop","MID"],["Tim Kleindienst","FWD"],["Franck Honorat","FWD"],["Nicolas Kühn","FWD"]],
"Hamburger SV": [["Daniel Heuer Fernandes","GK"],["Sebastiaan Bornauw","DEF"],["Jordan Torunarigha","DEF"],["Miro Muheim","DEF"],["David Møller Wolfe","DEF"],["Immanuël Pherai","MID"],["Fábio Vieira","MID"],["Albert Grønbæk","MID"],["Patson Daka","FWD"],["Terem Moffi","FWD"],["Yussuf Poulsen","FWD"]],
"FC Köln": [["Marvin Schwäbe","GK"],["Timo Hübers","DEF"],["Luka Lochoshvili","DEF"],["Borna Sosa","DEF"],["Jahmai Simpson-Pusey","DEF"],["Ellyes Skhiri","MID"],["Jan Thielmann","MID"],["Tom Krauß","MID"],["Luca Waldschmidt","FWD"],["Ragnar Ache","FWD"],["Linton Maina","FWD"]],
"Werder Bremen": [["Alexander Schlager","GK"],["Marco Friedl","DEF"],["Amos Pieper","DEF"],["Mitchell Weiser","DEF"],["Niklas Stark","DEF"],["Jens Stage","MID"],["Skelly Alvero","MID"],["Senne Lynen","MID"],["Marco Grüll","FWD"],["Justin Njinmah","FWD"],["Eren Dinkçi","FWD"]],
"SV Elversberg": [["Tim Boss","GK"],["Jan Gyamerah","DEF"],["Lukas Pinckert","DEF"],["Florian Le Joncour","DEF"],["Luca Sirch","DEF"],["Maurice Krattenmacher","MID"],["Amara Condé","MID"],["Francis Onyeka","MID"],["Luca Pfeiffer","FWD"],["David Mokwa","FWD"],["Noel Futkeu","FWD"]],
"Schalke 04": [["Kevin Müller","GK"],["Max Wöber","DEF"],["Robin Gosens","DEF"],["Nikola Katić","DEF"],["Timo Becker","DEF"],["Éric Dina-Ebimbe","MID"],["Ron Schallenberg","MID"],["Adil Aouchiche","MID"],["Edin Džeko","FWD"],["Bryan Lasme","FWD"],["Kenan Karaman","FWD"]],
"SC Paderborn": [["Markus Schubert","GK"],["Felix Götze","DEF"],["Jonah Sticker","DEF"],["Tjark Scheller","DEF"],["Niklas Mohr","DEF"],["Sebastian Klaas","MID"],["Raphael Obermair","MID"],["Ruben Müller","MID"],["Sven Michel","FWD"],["Steffen Tigges","FWD"],["Kennedy Okpala","FWD"]],

"Paris Saint-Germain": [["Lucas Chevalier","GK"],["Achraf Hakimi","DEF"],["Marquinhos","DEF"],["Nuno Mendes","DEF"],["Willian Pacho","DEF"],["Vitinha","MID"],["João Neves","MID"],["Fabián Ruiz","MID"],["Ousmane Dembélé","FWD"],["Désiré Doué","FWD"],["Khvicha Kvaratskhelia","FWD"]],
"RC Lens": [["Robin Risser","GK"],["Jean-Clair Todibo","DEF"],["Jonathan Gradit","DEF"],["Matthieu Udol","DEF"],["Maik Nawrocki","DEF"],["Amadou Haïdara","MID"],["Thorgan Hazard","MID"],["Michaël Cuisance","MID"],["Odsonne Édouard","FWD"],["Florian Thauvin","FWD"],["Florian Sotoca","FWD"]],
"LOSC Lille": [["Berke Özer","GK"],["Alexsandro","DEF"],["Tiago Santos","DEF"],["Nathan Ngoy","DEF"],["Romain Perraud","DEF"],["Benjamin André","MID"],["Hákon Haraldsson","MID"],["Nabil Bentaleb","MID"],["Olivier Giroud","FWD"],["Hamza Igamane","FWD"],["Dilane Bakwa","FWD"]],
"Olympique Lyonnais": [["Dominik Greif","GK"],["Nicolás Tagliafico","DEF"],["Moussa Niakhaté","DEF"],["Abner","DEF"],["Clinton Mata","DEF"],["Corentin Tolisso","MID"],["Tyler Morton","MID"],["Pavel Šulc","MID"],["Loïs Openda","FWD"],["Ernest Nuamah","FWD"],["Julien Duranville","FWD"]],
"Olympique de Marseille": [["Jeffrey de Lange","GK"],["Nayef Aguerd","DEF"],["CJ Egan-Riley","DEF"],["Derek Cornelius","DEF"],["Ulisses Garcia","DEF"],["Pierre-Emile Højbjerg","MID"],["Angel Gomes","MID"],["Amine Harit","MID"],["Pierre-Emerick Aubameyang","FWD"],["Amine Gouiri","FWD"],["Igor Paixão","FWD"]],
"Stade Rennais": [["Brice Samba","GK"],["Lilian Brassier","DEF"],["Anthony Rouault","DEF"],["Przemysław Frankowski","DEF"],["Quentin Merlin","DEF"],["Seko Fofana","MID"],["Adrien Thomasson","MID"],["Ludovic Blas","MID"],["Breel Embolo","FWD"],["Esteban Lepaul","FWD"],["Mousa Al Tamari","FWD"]],
"AS Monaco": [["Lukáš Hrádecký","GK"],["Vanderson","DEF"],["Jordan Teze","DEF"],["Mohammed Salisu","DEF"],["Eric Dier","DEF"],["Aleksandr Golovin","MID"],["Denis Zakaria","MID"],["Lamine Camara","MID"],["Folarin Balogun","FWD"],["Ansu Fati","FWD"],["Mika Biereth","FWD"]],
"RC Strasbourg": [["Filip Jörgensen","GK"],["Ismaël Doukouré","DEF"],["Abakar Sylla","DEF"],["Guela Doué","DEF"],["Andrew Omobamidele","DEF"],["Gio Reyna","MID"],["Sebastian Nanasi","MID"],["Mathis Amougou","MID"],["Joaquín Panichelli","FWD"],["Sékou Mara","FWD"],["Fabio Baldé","FWD"]],
"Toulouse FC": [["Guillaume Restes","GK"],["Rasmus Nicolaisen","DEF"],["Mark McKenzie","DEF"],["David Odogu","DEF"],["Christ Tapé","DEF"],["Cristian Cásseres Jr.","MID"],["Aron Dønnum","MID"],["Niklas Schmidt","MID"],["Yann-Alexandre Gboho","FWD"],["Ilyas Azizi","FWD"],["Santiago Hidalgo","FWD"]],
"FC Lorient": [["Yvon Mvogo","GK"],["Montassar Talbi","DEF"],["Isaak Touré","DEF"],["Formose Mendy","DEF"],["Dembo Sylla","DEF"],["Jean-Victor Makengo","MID"],["Théo Le Bris","MID"],["Noah Cadiou","MID"],["Mamadou Koné","FWD"],["Aiyegun Tosin","FWD"],["Souleymane Faye","FWD"]],
"Paris FC": [["Kevin Trapp","GK"],["Hamari Traoré","DEF"],["Otávio","DEF"],["Thibault De Smet","DEF"],["Moustapha Mbow","DEF"],["Maxime López","MID"],["Pierre Lees-Melou","MID"],["Vincent Marchetti","MID"],["Moses Simon","FWD"],["Jonathan Ikoné","FWD"],["Lassine Sinayoko","FWD"]],
"Stade Brestois": [["Grégoire Coudert","GK"],["Brendan Chardonnet","DEF"],["Bradley Locko","DEF"],["Kenny Lala","DEF"],["Justin Bourgault","DEF"],["Lucas Tousart","MID"],["Joris Chotard","MID"],["Hugo Magnetti","MID"],["Ludovic Ajorque","FWD"],["Mama Baldé","FWD"],["Romain Del Castillo","FWD"]],
"Angers SCO": [["Anthony Lopes","GK"],["Jordan Lefort","DEF"],["Joseph Kalulu","DEF"],["Carlens Arcus","DEF"],["Maël Gernigon","DEF"],["Haris Belkebla","MID"],["Branco van den Boomen","MID"],["Louis Mouton","MID"],["Jim Allevinah","FWD"],["Amine El Ouazzani","FWD"],["Prosper Peter","FWD"]],
"Le Havre AC": [["Gauthier Gallon","GK"],["Ahmed Touba","DEF"],["Stephan Zagadou","DEF"],["Timothée Pembélé","DEF"],["Fodé Doucouré","DEF"],["Abdoulaye Touré","MID"],["Rassoul N'Diaye","MID"],["Amir Richardson","MID"],["Josh Maja","FWD"],["Ally Samatta","FWD"],["Andy Logbo","FWD"]],
"AJ Auxerre": [["Paul Nardi","GK"],["Sinaly Diomandé","DEF"],["Francisco Sierralta","DEF"],["Bryan Okoh","DEF"],["Christ Makosso","DEF"],["Naouirou Ahamada","MID"],["Assane Dioussé","MID"],["Romain Faivre","MID"],["Theo Bair","FWD"],["Danny Namaso","FWD"],["Aristide Zossou","FWD"]],
"OGC Nice": [["Yehvann Diouf","GK"],["Jonathan Clauss","DEF"],["Moïse Bombito","DEF"],["Melvin Bard","DEF"],["Mohamed Abdelmonem","DEF"],["Morgan Sanson","MID"],["Hichem Boudaoui","MID"],["Salis Abdul Samed","MID"],["Terem Moffi","FWD"],["Mohamed-Ali Cho","FWD"],["Sofiane Diop","FWD"]],
"Le Mans FC": [["Nicolas Kocik","GK"],["Djibril Sidibé","DEF"],["Yasser Larouci","DEF"],["Raúl Torrente","DEF"],["Samuel Yohou","DEF"],["Adil Bourabaa","MID"],["Milan Robin","MID"],["Daouda Traoré","MID"],["Bilal Brahimi","FWD"],["Dame Guèye","FWD"],["Antoine Rabillard","FWD"]],
"ESTAC Troyes": [["Zacharie Boucher","GK"],["Adrien Monfray","DEF"],["Yvann Titi","DEF"],["Noah Donkor","DEF"],["Ismaël Boura","DEF"],["Iron Gomis","MID"],["Antoine Mille","MID"],["Roman Murcy","MID"],["Renaud Ripart","FWD"],["Ibrahim Traoré","FWD"],["Amadou Diakité","FWD"]]
};

var REFEREES_BY_LEAGUE = {
  "epl": [
    { name:"Michael Oliver", cpg:3.2, mult:0.83, tendency:"Lets the game flow, cards sparingly" },
    { name:"Anthony Taylor", cpg:4, mult:1.04, tendency:"Close to the league-average card rate" },
    { name:"Chris Kavanagh", cpg:4.3, mult:1.12, tendency:"Close to the league-average card rate" },
    { name:"Stuart Attwell", cpg:4.9, mult:1.27, tendency:"Quick to reach for cards" },
    { name:"Craig Pawson", cpg:2.8, mult:0.73, tendency:"Lets the game flow, cards sparingly" },
    { name:"Paul Tierney", cpg:3.3, mult:0.86, tendency:"Lets the game flow, cards sparingly" },
    { name:"Peter Bankes", cpg:4.2, mult:1.09, tendency:"Close to the league-average card rate" },
    { name:"Simon Hooper", cpg:4.1, mult:1.06, tendency:"Close to the league-average card rate" },
  ],
  "laliga": [
    { name:"Jesús Gil Manzano", cpg:4.9, mult:0.97, tendency:"Close to the league-average card rate" },
    { name:"José María Sánchez Martínez", cpg:4.9, mult:0.97, tendency:"Close to the league-average card rate" },
    { name:"Juan Martínez Munuera", cpg:4.3, mult:0.85, tendency:"Lets the game flow, cards sparingly" },
    { name:"Ricardo De Burgos Bengoetxea", cpg:4.1, mult:0.81, tendency:"Lets the game flow, cards sparingly" },
    { name:"Isidro Díaz de Mera Escuderos", cpg:5.5, mult:1.08, tendency:"Close to the league-average card rate" },
    { name:"César Soto Grado", cpg:5.3, mult:1.04, tendency:"Close to the league-average card rate" },
    { name:"Alejandro Hernández Hernández", cpg:5.8, mult:1.14, tendency:"Quick to reach for cards" },
    { name:"Mateo Busquets Ferrer", cpg:5.8, mult:1.14, tendency:"Quick to reach for cards" },
  ],
  "seriea": [
    { name:"Daniele Doveri", cpg:3.3, mult:0.77, tendency:"Lets the game flow, cards sparingly" },
    { name:"Marco Guida", cpg:4.1, mult:0.95, tendency:"Close to the league-average card rate" },
    { name:"Simone Sozza", cpg:4.2, mult:0.97, tendency:"Close to the league-average card rate" },
    { name:"Davide Massa", cpg:5.2, mult:1.21, tendency:"Quick to reach for cards" },
    { name:"Fabio Maresca", cpg:5.2, mult:1.21, tendency:"Quick to reach for cards" },
    { name:"Michael Fabbri", cpg:4.3, mult:1, tendency:"Close to the league-average card rate" },
    { name:"Federico La Penna", cpg:4.3, mult:1, tendency:"Close to the league-average card rate" },
    { name:"Maurizio Mariani", cpg:3.9, mult:0.9, tendency:"Close to the league-average card rate" },
  ],
  "bundesliga": [
    { name:"Felix Zwayer", cpg:4.7, mult:1.2, tendency:"Quick to reach for cards" },
    { name:"Deniz Aytekin", cpg:4.3, mult:1.1, tendency:"Close to the league-average card rate" },
    { name:"Daniel Siebert", cpg:3.4, mult:0.87, tendency:"Lets the game flow, cards sparingly" },
    { name:"Tobias Stieler", cpg:3.3, mult:0.84, tendency:"Lets the game flow, cards sparingly" },
    { name:"Sascha Stegemann", cpg:3.6, mult:0.92, tendency:"Close to the league-average card rate" },
    { name:"Tobias Welz", cpg:5.1, mult:1.3, tendency:"Quick to reach for cards" },
    { name:"Christian Dingert", cpg:4, mult:1.02, tendency:"Close to the league-average card rate" },
    { name:"Bastian Dankert", cpg:2.9, mult:0.74, tendency:"Lets the game flow, cards sparingly" },
  ],
  "ligue1": [
    { name:"François Letexier", cpg:4.8, mult:1.16, tendency:"Quick to reach for cards" },
    { name:"Clément Turpin", cpg:3.3, mult:0.8, tendency:"Lets the game flow, cards sparingly" },
    { name:"Ruddy Buquet", cpg:3.1, mult:0.75, tendency:"Lets the game flow, cards sparingly" },
    { name:"Willy Delajod", cpg:3.4, mult:0.82, tendency:"Lets the game flow, cards sparingly" },
    { name:"Bastien Dechepy", cpg:4.9, mult:1.18, tendency:"Quick to reach for cards" },
    { name:"Jérémie Pignard", cpg:4.7, mult:1.14, tendency:"Quick to reach for cards" },
    { name:"Jérémy Stinat", cpg:4.3, mult:1.04, tendency:"Close to the league-average card rate" },
    { name:"Marc Bollengier", cpg:4.6, mult:1.11, tendency:"Close to the league-average card rate" },
  ],
};

  global.FORMCHECK_DATA = { RAW_LEAGUES: RAW_LEAGUES, EURO_STRENGTH: EURO_STRENGTH, CUPS: CUPS, MATCHES: MATCHES,
    ROSTERS: ROSTERS, REFEREES_BY_LEAGUE: REFEREES_BY_LEAGUE,
    SNAPSHOT_DATE: "2026-09-03" };
})(window);
